version: '3'

services:
    mosquitto-service:
        build: ./mosquitto
        network_mode: "host"
        volumes:
            - /opt/mosquitto:/opt/mosquitto
            - /opt/mosquitto/logs:/var/log/mosquitto
            - /opt/mosquitto/certs/trusted:/etc/mosquitto/certs
        ports:
            - 1883:1883
            - 8883:8883
            - 9883:9883

    openhab:
        image: "openhab/openhab:2.1.0-armhf-debian"
        restart: always
        network_mode: host
        tty: true
        volumes:
            - "/etc/localtime:/etc/localtime:ro"
            - "/etc/timezone:/etc/timezone:ro"
            - "openhan/addons:/openhab/addons"
            - "openhab/conf:/openhab/conf"
            - "openhab/userdata:/openhab/userdata"
        devices:
            - "/dev/ttyUSB0"
        environment:
            OPENHAB_HTTP_PORT: "8080"
            OPENHAB_HTTPS_PORT: "8443"
